### PR TITLE
Always provide polyfill for dependencies if WP or Gutenberg plugin is not supported; ensure onboarding wizard works on < WP 5.6

### LINKED ISSUE #6194: WP 4.9 + Gutenberg: `Uncaught TypeError: Object(...) is not a function` on settings page
## Bug Description

As of AMP 2.1, the AMP settings page now loads a blank screen with the following error in the console with WP 4.9:

```
amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:9 Uncaught TypeError: Object(...) is not a function
    at amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:9
    at Object.<anonymous> (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:9)
    at n (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1)
    at Module.<anonymous> (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29)
    at Module.<anonymous> (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29)
    at n (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1)
    at Object.<anonymous> (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29)
    at n (amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1)
    at amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
    at amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:9
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:9
n @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29
n @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:29
n @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
(anonymous) @ amp-settings.js?ver=a588d4c54efa16d65aeca1df56a057dd:1
```

## Expected Behaviour

The settings page should load as usual 🙏 

## Steps to reproduce

1. Use latest 4.9 version of WordPress
2. Install Gutenberg 4.9.0 (not possible to install newer version)
2. Install and activate the latest version of AMP (currently 2.1.1)
3. Navigate to the AMP settings page
4. See screen as shown above

## Screenshots

image

## Additional context

 - WordPress version: 4.9.17
 - Plugin version: 2.1.1
 - Gutenberg plugin version (if applicable): 4.9.0
 - PHP version: 7.4.19

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

Test cases to check, if support is absent:

* Block editor should show upgrade notice.
* Classic editor (without Gutemberg in 4.9 and w/ Classic Editor plugin in 5.0+) should show notice with AMP enabled status.
* Validation Counts should be omitted from admin menu.
* AMP Settings screen should work as expected, but with an upgrade notice shown.
* Onboarding Wizard should work normally.
* Paired browsing should not be available.
* AMP Customizer _does_ still work.

Environments to check:

* WordPress 4.9 with Gutenberg 4.9.0
* WordPress 4.9 without Gutenberg
* WordPress 5.5.5 without Gutenberg nor Classic Editor
* WordPress 5.5.5 with Gutenberg 8.9.0
* WordPress 5.5.5 with Classic Editor
* WordPress 5.6.4 without Gutenberg nor Classic Editor
* WordPress 5.6.4 with Gutenberg 10.2.0
* WordPress 5.6.4 with Classic Editor
* WordPress 5.7 without Gutenberg nor Classic Editor
* WordPress 5.7 with latest Gutenberg
* WordPress 5.7 with Classic Editor

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by pierlon**
## Summary

Fixes #6194.

This PR ensures that the polyfilled dependencies are always registered if WP or the active Gutenberg plugin is known to have outdated dependencies, which can sometimes cause some plugin screens to not work as intended.

Also, polyfills are now provided for the onboarding wizard so that it is operable on WP < 5.6. 

## Checklist

- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/wiki/Engineering-Guidelines) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

File: includes/admin/functions.php [hunk 1]
```diff
@@ -192,9 +193,6 @@ function amp_bootstrap_admin() {
  * @return bool
  */
 function amp_should_use_new_onboarding() {
-	if ( version_compare( get_bloginfo( 'version' ), '5.0', '<' ) ) {
-		return false;
-	}
-
-	return true;
+	$dependency_support = Services::get( 'dependency_support' );
+	return $dependency_support->has_support();
```
Comment (westonruter) [inline includes/admin/functions.php]: To confirm, this means that the onboarding wizard will only be available in WP 5.6+ (or Gutenberg 9.2.0+).

File: src/DependencySupport.php [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+	const WP_MIN_VERSION = '5.6';
+
+	/**
+	 * Get the action to use for registering the service.
+	 *
+	 * @return string Registration action to use.
+	 */
+	public static function get_registration_action() {
+		return 'plugins_loaded';
+	}
```
Comment (westonruter) [inline src/DependencySupport.php]: Is `Delayed` necessary since the services get registered at `plugins_loaded` anyway?

File: src/DependencySupport.php [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+ */
+
+namespace AmpProject\AmpWP;
+
+use AmpProject\AmpWP\Infrastructure\Delayed;
+use AmpProject\AmpWP\Infrastructure\Service;
+
+/**
+ * DependencySupport class.
+ *
```
Comment (westonruter) [inline src/DependencySupport.php:14]:
```suggestion
 *
 * @since 2.1.2
```

File: tests/php/validation/test-class-amp-validation-manager.php [hunk 4]
```diff
@@ -522,8 +522,8 @@ public function test_add_validation_error_sourcing_gutenberg() {
 		if ( ! function_exists( 'do_blocks' ) ) {
 			$this->markTestSkipped( 'Gutenberg not active.' );
 		}
-		if ( version_compare( get_bloginfo( 'version' ), '4.9', '<' ) ) {
-			$this->markTestSkipped( 'The WP version is less than 4.9, so Gutenberg did not init.' );
+		if ( version_compare( get_bloginfo( 'version' ), '5.0', '<' ) ) {
+			$this->markTestSkipped( 'Gutenberg for WP < 5.0 is not supported.' );
```
Comment (westonruter) [inline tests/php/validation/test-class-amp-validation-manager.php:526]: Is this change and the latter correct since in WP 4.9 the 4.9.0 version of Gutenberg is installed?

**Comment by westonruter** [comment]
Todo: Onboarding Wizard should work on WP<5.6 if the AMP Settings screen is also supposed to work.

**Comment by pierlon** [comment]
> Todo: Onboarding Wizard should work on WP<5.6 if the AMP Settings screen is also supposed to work.

Done in https://github.com/ampproject/amp-wp/pull/6225/commits/f0962b18f42dc894107f4c172d3d135cc0752187. The onboarding wizard should be operable as far back as WP 4.9.

File: src/DependencySupport.php (hunk 3 above)
Comment (pierlon) [reply src/DependencySupport.php:14]: Done in 260734553a6bbe667fa5d05961c314cc99c37fe3.

File: includes/admin/functions.php (hunk 1 above)
Comment (pierlon) [reply includes/admin/functions.php]: Resolving since outdated since https://github.com/ampproject/amp-wp/pull/6225/commits/f0962b18f42dc894107f4c172d3d135cc0752187.

File: src/DependencySupport.php (hunk 2 above)
Comment (pierlon) [reply src/DependencySupport.php]: Resolving since outdated since https://github.com/ampproject/amp-wp/pull/6225/commits/260734553a6bbe667fa5d05961c314cc99c37fe3.

File: tests/php/validation/test-class-amp-validation-manager.php (hunk 4 above)
Comment (pierlon) [reply tests/php/validation/test-class-amp-validation-manager.php:526]: I meant 'not supported' in the sense that the `do_blocks` hook occurs at priority 7 instead of 9 in GB 4.9.0, so the functionality being tested here would fail.

**Review by delawski — APPROVED** [review]
The code, specifically the JS/Gutenberg-related part, looks good to me.

I've tested out the update on WordPress 4.9.8 with Gutenberg 4.9.0 activated and can confirm that both the Settings page and the Wizard work well now.

File: webpack.config.js [hunk 5]
```diff
@@ -160,7 +160,7 @@ const customizer = {
 
 const WORDPRESS_NAMESPACE = '@wordpress/';
 const BABEL_NAMESPACE = '@babel/';
-const gutenbergPackages = [ '@babel/polyfill', '@wordpress/dom-ready', '@wordpress/i18n', '@wordpress/hooks', '@wordpress/url' ].map(
+const gutenbergPackages = [ '@babel/polyfill', '@wordpress/dom-ready', '@wordpress/i18n', '@wordpress/hooks', '@wordpress/html-entities', '@wordpress/url' ].map(
```
Comment (westonruter) [inline webpack.config.js:163]: @pierlon The `@wordpress/html-entities` is a new dependency that we use which needs to be polyfilled or else an error occurs?

Comment (pierlon) [reply webpack.config.js:163]: It's needed for the onboarding wizard to load in WP 4.9.

**Comment by westonruter** [comment]
I'm testing this in WP 4.9.x and I'm getting a fatal error when going to the WP Dashboard:

```
Fatal error: Uncaught Error: Call to undefined function AmpProject\AmpWP\Admin\get_current_screen() in /app/public/wp-content/plugins/amp/src/Admin/Polyfills.php:50
Stack trace:
#0 /app/public/wp-content/plugins/amp/src/Infrastructure/ServiceBasedPlugin.php(301): AmpProject\AmpWP\Admin\Polyfills->register()
#1 /app/public/wp-content/plugins/amp/src/Infrastructure/ServiceBasedPlugin.php(207): AmpProject\AmpWP\Infrastructure\ServiceBasedPlugin->register_service('admin.polyfills', 'AmpProject\\AmpW...')
#2 /app/public/wp-includes/class-wp-hook.php(286): AmpProject\AmpWP\Infrastructure\ServiceBasedPlugin->AmpProject\AmpWP\Infrastructure\{closure}('')
#3 /app/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 /app/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /app/public/wp-content/plugins/amp/src/Admin/PairedBrowsing.php(156): do_action('amp_register_po...')
#6 /app/public/wp-content/plugins/amp/src/Admin/PairedBrowsing.php(129): AmpProject\AmpWP\Admin\PairedBrowsing->init_clien in /app/public/wp-content/plugins/amp/src/Admin/Polyfills.php on line 50
```

Investigating…

**Comment by westonruter** [comment]
> I'm getting a fatal error when going to the WP Dashboard

Correction: when I go to the frontend.

**Comment by westonruter** [comment]
It looks like we need to make `PairedBrowsing` also incorporate `DependencySupport` so that it is only available if a sufficient version of Core or Gutenberg is installed. We should also make sure that `function_exists( 'get_current_screen' )`.

File: src/Admin/Polyfills.php [hunk 6]
```diff
@@ -32,10 +34,24 @@ public static function get_registration_action() {
...
+	public static function is_needed() {
+		return ! Services::get( 'dependency_support' )->has_support();
+	}
+
 	/**
 	 * Runs on instantiation.
 	 */
 	public function register() {
+		$screen = get_current_screen();
+		if ( ! empty( $screen->is_block_editor ) ) {
```
Comment (westonruter) [inline src/Admin/Polyfills.php:51]: This will prevent a fatal error from happening in the context of the frontend:

```suggestion
		if ( function_exists( 'get_current_screen' ) ) {
			$screen = get_current_screen();
			if ( ! empty( $screen->is_block_editor ) ) {
				return;
			}
		}
```

File: src/Admin/Polyfills.php [hunk 7]
```diff
@@ -32,10 +34,24 @@ public static function get_registration_action() {
...
+			return;
+		}
```
Comment (westonruter) [inline src/Admin/Polyfills.php]: This will prevent a fatal error from happening when polyfills are registered on the frontend:

```suggestion
		if ( function_exists( 'get_current_screen' ) ) {
			$screen = get_current_screen();
			if ( ! empty( $screen->is_block_editor ) ) {
				return;
			}
		}
```

**Comment by westonruter** [comment]
> It looks like we need to make `PairedBrowsing` also incorporate `DependencySupport` so that it is only available if a sufficient version of Core or Gutenberg is installed.

This is important because at present the paired browsing client scripts just won't get printed because when their dependencies aren't registered, and that just causes the paired browsing app to not work properly. So any paired browsing UI functionality should be disabled if `! has_support`.

File: tests/php/src/Admin/PairedBrowsingTest.php [hunk 8]
```diff
@@ -47,7 +48,12 @@ public function test_is_needed() {
 
 		AMP_Options_Manager::update_option( Option::THEME_SUPPORT, AMP_Theme_Support::READER_MODE_SLUG );
 		AMP_Options_Manager::update_option( Option::READER_THEME, get_stylesheet() );
-		$this->assertTrue( PairedBrowsing::is_needed() );
+
+		if ( Services::get( 'dependency_support' )->has_support() ) {
+			$this->assertTrue( PairedBrowsing::is_needed() );
+		} else {
+			$this->assertFalse( PairedBrowsing::is_needed() );
+		}
```
Comment (westonruter) [inline tests/php/src/Admin/PairedBrowsingTest.php]: Looks like this needs to be copied to replace line 47 as well.

**Comment by westonruter** [comment]
@pierlon I found the AMP Enabled link is no longer working in the classic editor in 4.9:

> image

And when Gutenberg 4.9.0 is active, there is no notice about AMP functionality being unavailable:

> image

**Comment by westonruter** [comment]
> And when Gutenberg 4.9.0 is active, there is no notice about AMP functionality being unavailable:

It seems the issue here is that `WP_Screen::$is_block_editor` is not set in Gutenberg 4.9.0.

> I found the AMP Enabled link is no longer working in the classic editor in 4.9:

We may want to show a notice to ask the user to upgrade the WP version here too. If so, the notice we show in the block editor should not tell the user to resort to the Classic Editor plugin.

**Comment by pierlon** [comment]
@westonruter can you confirm if https://github.com/ampproject/amp-wp/pull/6225/commits/98e259c6d7a7db2637aa05a738c0e59346600ea0 fixes the AMP Enabled link in the classic editor?

**Comment by westonruter** [comment]
> can you confirm if [98e259c](https://github.com/ampproject/amp-wp/commit/98e259c6d7a7db2637aa05a738c0e59346600ea0) fixes the AMP Enabled link in the classic editor?

@pierlon I can see the notice in the 4.9.0 _block_ editor, but the AMP toggle in 4.9 when Gutenberg is deactivated is still inert:

https://user-images.githubusercontent.com/134745/118566103-3cb4f880-b728-11eb-9d85-4a6f30288c29.mov

**Comment by westonruter** [comment]
I think we should replace that line with a notice to ask the user to upgrade.

**Comment by westonruter** [comment]
With d2b79c1, users of unsupported versions of WordPress will see:

image

**Comment by westonruter** [comment]
On the Settings screen, the user sees the notice repurposed from what was originally in the `Welcome` component:

image

File: includes/templates/amp-enabled-classic-editor-toggle.php [hunk 9]
```diff
@@ -23,38 +25,50 @@
...
-					<strong><?php esc_html_e( 'AMP Unavailable', 'amp' ); ?></strong>
-				</p>
-				<?php foreach ( $error_messages as $error_message ) : ?>
+
+	<?php if ( ! Services::get( 'dependency_support' )->has_support_from_core() ) : ?>
+		<div class="notice notice-info notice-alt inline">
+			<p>
+				<strong>
+
+				</strong>
```
Comment (westonruter) [inline includes/templates/amp-enabled-classic-editor-toggle.php]:
```suggestion
```

File: includes/admin/class-amp-post-meta-box.php [hunk 10]
```diff
@@ -163,6 +163,11 @@ public function enqueue_admin_assets() {
 
 		wp_styles()->add_data( self::ASSETS_HANDLE, 'rtl', 'replace' );
 
+		// Abort if version of WordPress is too old.
+		if ( ! Services::get( 'dependency_support' )->has_support_from_core() ) {
```
Comment (westonruter) [inline includes/admin/class-amp-post-meta-box.php:167]: I chose to go with checking for core support here rather than support in general because I figure it would be a bad idea to try to `amp_register_polyfills` on the edit post screen, not knowing what possible conflicts could result.

File: src/Editor/EditorSupport.php [hunk 11]
```diff
@@ -51,7 +50,12 @@ public function maybe_show_notice() {
 			return;
 		}
 
-		if ( ! isset( $screen->is_block_editor ) || false === $screen->is_block_editor ) {
+		if (
+			! empty( $screen->is_block_editor )
+			||
+			// Applicable to Gutenberg v5.5.0 and older.
+			( function_exists( 'is_gutenberg_page' ) && ! is_gutenberg_page() )
+		) {
```
Comment (westonruter) [inline src/Editor/EditorSupport.php]: Is this not inverted from what it was before? The `! empty( $screen->is_block_editor )` condition means it _is_ the block editor, and we should only be returning here if it is not the block editor, right?

```suggestion
		$is_block_editor = (
			! empty( $screen->is_block_editor )
			||
			// Applicable to Gutenberg v5.5.0 and older.
			( function_exists( 'is_gutenberg_page' ) && is_gutenberg_page() )
		);
		if ( ! $is_block_editor ) {
```

Comment (westonruter) [reply src/Editor/EditorSupport.php]: Otherwise it seems the notice would never be displayed when Gutenberg 5.6+ is active.

Comment (pierlon) [reply src/Editor/EditorSupport.php]: Whoops yea you're right.

Comment (westonruter) [reply src/Editor/EditorSupport.php]: Indeed, when testing with WordPress 5.1.3 and Gutenberg 5.6.1 I see no notice.

File: tests/php/src/Editor/EditorSupportTest.php [hunk 12]
```diff
@@ -165,4 +143,32 @@ public function test_maybe_show_notice_with_cpt_supporting_gutenberg_but_not_amp
...
+			'my-gb-post-type',
+			[
+				'public'       => true,
+				'show_in_rest' => true,
+				'supports'     => [ 'editor' ],
+			]
+		);
+
+		set_current_screen( 'edit.php' );
+		$post = $this->factory()->post->create( [ 'post_type' => 'my-gutenberg-post-type' ] );
```
Comment (westonruter) [inline tests/php/src/Editor/EditorSupportTest.php]: This test is failing, at least because `my-gb-post-type` is the post type defined but `my-gutenberg-post-type` is the post type created, but neither of these are among the `AMP_Post_Type_Support::get_eligible_post_types()`.

**Comment by westonruter** [comment]
Fixing test…

**Comment by westonruter** [comment]
See test cases in the description on https://github.com/ampproject/amp-wp/issues/6194.

**Review by westonruter — APPROVED** [review]
